steps:
  - name: Remove conflicting packages
    run: |
      sudo apt-get remove -y containerd || true

  - name: Install Docker
    run: |
      curl -fsSL https://get.docker.com -o get-docker.sh
      sudo sh get-docker.sh
