name: Run Xray and Generate VLESS Link

on:
  workflow_dispatch:

jobs:
  run-xray:
    runs-on: ubuntu-latest

    steps:
    - name: Install Required Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y curl wget unzip jq

    - name: Download and Install Xray
      run: |
        mkdir -p xray && cd xray
        curl -L -o xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
        unzip xray.zip
        chmod +x xray
        sudo mv xray /usr/local/bin/

    - name: Create Xray Configuration Directory
      run: sudo mkdir -p /etc/xray

    - name: Create Xray Configuration File
      run: |
        sudo tee /etc/xray/config.json > /dev/null <<EOF
        {
          "log": {
            "loglevel": "info"
          },
          "inbounds": [
            {
              "port": 443,
              "protocol": "vless",
              "settings": {
                "clients": [
                  {
                    "id": "$(uuidgen)",
                    "level": 0,
                    "email": "test@example.com"
                  }
                ],
                "decryption": "none"
              },
              "streamSettings": {
                "network": "tcp"
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom",
              "settings": {}
            }
          ]
        }
        EOF

    - name: Start Xray Server
      run: |
        nohup sudo xray -config /etc/xray/config.json &

    - name: Get Public IP Address
      id: get_ip
      run: |
        PUBLIC_IP=$(curl -s ifconfig.me)
        echo "::set-output name=ip::$PUBLIC_IP"

    - name: Generate VLESS Link
      id: generate_link
      run: |
        CLIENT_ID=$(sudo jq -r '.inbounds[0].settings.clients[0].id' /etc/xray/config.json)
        PUBLIC_IP=${{ steps.get_ip.outputs.ip }}
        echo "vless://${CLIENT_ID}@${PUBLIC_IP}:443?encryption=none" > vless_link.txt

    - name: Output VLESS Link
      run: |
        cat vless_link.txt
      continue-on-error: true

    - name: Set VLESS Link as Output
      id: output
      run: echo "::set-output name=vless_link::$(cat vless_link.txt)"

    - name: Display Link
      run: |
        echo "VLESS Link: ${{ steps.output.outputs.vless_link }}"
